devShells.bootstrap: fix linker error
Started getting the following error when I tried to run `cargo build`
after the module refactoring. Switched to the standard `mkShell` instead
of the one without GCC.

error: linker `cc` not found
  |
  = note: No such file or directory (os error 2)

error: could not compile `nix-derivation-parser` (bin "nix-derivation-parser") due to 1 previous error